CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  openid TEXT UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS spaces (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  type TEXT,
  layout TEXT,
  images TEXT,
  long_term_memory TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  space_id INTEGER,
  short_term_memory TEXT,
  status TEXT DEFAULT 'uploaded',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_responses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id INTEGER,
  questions TEXT,
  answers TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS interventions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id INTEGER,
  tier TEXT,
  diagnosis TEXT,
  actions TEXT,
  image_prompts TEXT,
  rendered_images TEXT,
  saved_to_next INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS next_actions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  intervention_id INTEGER,
  status TEXT DEFAULT 'pending',
  before_images TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME
);

CREATE TABLE IF NOT EXISTS feedbacks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  next_action_id INTEGER,
  after_images TEXT,
  user_note TEXT,
  missed_steps TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS letters (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  feedback_id INTEGER,
  content TEXT,
  signature TEXT DEFAULT '—— Nobi',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
